replicaCount: 1

image:
  repository: xlen911/booking-service
  tag: "1.0.16"
  pullPolicy: Always

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: booking.dev.company.internal
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3

configMap:
  data:
    NODE_ENV: "development"
    LOG_LEVEL: "debug"
    SERVICE_NAME: "booking-service"
    SERVICE_VERSION: "1.0.15"